// Copyright 2019, Trail of Bits. All rights reserved.

#pragma once

#include <drlojekyll/Rel/Query.h>

namespace hyde {

class QueryBuilderImpl;
class SIPSScorer;
class SIPSGenerator;

// Builds up a query.
class QueryBuilder {
 public:

  QueryBuilder(void);
  ~QueryBuilder(void);

  // Build an insertion query for the best scoring, according to `scorer`,
  // permutation of some clause body, given some predicate, as generated by
  // `generator`.
  Query BuildInsert(SIPSScorer &scorer, SIPSGenerator &generator);

 private:
  std::unique_ptr<QueryBuilderImpl> impl;
};

}  // namespace hyde
