// Copyright 2019, Trail of Bits. All rights reserved.

#include <drlojekyll/Sema/SIPSScore.h>

#include <string>

namespace hyde {

class DefaultSIPSScorer::Impl {
 public:
  int best_permutation{-1};
  int current_permutation{-1};
  std::string current_score;
  std::string best_score;
};

DefaultSIPSScorer::DefaultSIPSScorer(void)
    : impl(new Impl) {}

DefaultSIPSScorer::~DefaultSIPSScorer(void) {}

int DefaultSIPSScorer::BestPermutation(void) const {
  return impl->best_permutation;
}

void DefaultSIPSScorer::Begin(ParsedPredicate) {
  impl->current_permutation++;
  impl->current_score.clear();
}

void DefaultSIPSScorer::Commit(ParsedPredicate) {
  std::reverse(impl->current_score.begin(), impl->current_score.end());
  if (impl->best_score.empty() || impl->current_score < impl->best_score) {
    impl->best_score.swap(impl->current_score);
    impl->best_permutation = impl->current_permutation;
  }
}

void DefaultSIPSScorer::EnterFromWhereSelect(
    ParsedPredicate, ParsedDeclaration,
    const Column *where_begin, const Column *where_end,
    const Column *select_begin, const Column *select_end) {
  for (auto col = select_begin; col < select_end; ++col) {
    impl->current_score.push_back('\1');
  }
  for (auto col = where_begin; col < where_end; ++col) {
    impl->current_score.push_back('\0');
  }
}

void DefaultSIPSScorer::EnterFromSelect(
    ParsedPredicate, ParsedDeclaration,
    const Column *select_begin, const Column *select_end) {
  for (auto col = select_begin; col < select_end; ++col) {
    impl->current_score.push_back('\1');
  }
}

// Use `scorer` to find the best permutation that can be generated by
// `generator`, and then apply `visitor` to that permutation.
//
// Returns `true` if any permutation was visited, and `false` otherwise.
bool SIPSScorer::VisitBestScoringPermuation(
    SIPSScorer &scorer, SIPSVisitor &visitor, SIPSGenerator &generator) {

  auto best_index = scorer.BestPermutation();
  if (0 > best_index) {
    generator.Rewind();
    do {
      (void) generator.Visit(scorer);
    } while (generator.Advance());
    best_index = scorer.BestPermutation();
    if (0 > best_index) {
      return false;
    }
  }

  generator.Rewind();
  for (auto i = 0; i < best_index; ++i) {
    if (!generator.Advance()) {
      return false;
    }
  }

  generator.Visit(visitor);

  return true;
}

}  // namespace hyde
