name: Fuzz Testing

on:
  # Run on the default branch every day at 10:15
  schedule:
    - cron: "15 10 * * *"

  # Run when manually triggered.
  # See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  #
  # NOTE: If you update the default values here, make sure to also update the
  #       values in the following `env` section.
  workflow_dispatch:
    inputs:
      fuzz_seconds:
        description: "Maximum number of seconds to run the fuzzer"
        required: true
        default: "1200"

      timeout_seconds:
        description: "Number of seconds before the fuzzer treats the input as a timeout"
        required: true
        default: "5"

      max_length:
        description: "Maximum length of fuzzer-generated inputs"
        required: true
        default: "800"

      corpus_prune_threshold:
        description: "The number of corpus entries at which to try corpus minimization"
        required: true
        default: "500"

# Note: the following environment variables are duplicated from the default values
#       of the inputs specified in the `workflow_dispatch` trigger above.
#       The `workflow_dispatch` trigger support in GitHub Actions seems to have
#       a bunch of rough edges.  In particular, the default values show up as
#       expected in the GitHub web UI when manually triggering the job, but the
#       values are _not_ propagated reliably as `INPUT_*` environment variables,
#       and the default values do not seem to be programmatically accessible
#       within job steps via any actions context.
#
#       It seems difficult to avoid repeating ourselves for these default values,
#       so here we are.
env:
  FUZZ_SECONDS_DEFAULT: "1200"
  TIMEOUT_SECONDS_DEFAULT: "5"
  MAX_LENGTH_DEFAULT: "800"
  CORPUS_PRUNE_THRESHOLD_DEFAULT: "500"



jobs:
  fuzz1:
    name: Fuzz Ubuntu 20.04 / Clang 10 / Debug / Sanitizers
    runs-on: ubuntu-20.04

    env:
      FUZZ_RUN_DIR: "${{ github.workspace }}/fuzzer-run"

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install clang-10 ninja-build creduce

      - name: Configure
        run: >
          cmake -B build
          -G Ninja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=clang-10
          -DCMAKE_CXX_COMPILER=clang++-10
          -DENABLE_SANITIZERS=1
          -DENABLE_LIBFUZZER=1
          -DWARNINGS_AS_ERRORS=1
          -DENABLE_TESTS=0
          .

      - name: Build
        run: ninja -C build -j "$(nproc)"

      # Note: The following use of GitHub Actions cache mechanism is a hack to
      #       persist the fuzzer corpus and other generated artifacts from run
      #       to run in our CI.
      #
      #       The particular contents of the fuzzer corpus aren't especially
      #       important beyond the fact that they represent possibly
      #       hard-earned knowledge about inputs that evoke different behavior
      #       from the fuzz target.
      #
      #       During each run of this workflow, we deliberately try to get an
      #       "exact cache miss", and fall back to fetching the most recent
      #       cache entry with the `fuzz_run_dir-` prefix.  Then, when the job
      #       completes successfully, the cache will be updated.
      #
      #       Currently, cache entries are kept until they have no longer been
      #       accessed for 7 days, or until 5GB of cache has been consumed.
      #
      #       See https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows for more details.
      #
      #       This could be simplified if GitHub Actions cache mechanism had a
      #       way of explicitly forcing the cache to be updated upon job
      #       completion.  (Relevant: a fork of the cache action that does this: https://github.com/pat-s/always-upload-cache)
      #
      #       Alternatively, we may want to switch to some other mechanism for
      #       persisting the corpus, such as an S3 bucket.
      #
      #       See #76.
      - name: Cache fuzzer artifacts
        uses: actions/cache@v2
        with:
          path: ${{ env.FUZZ_RUN_DIR }}
          key: fuzz_run_dir-${{ github.run_id }}
          restore-keys: fuzz_run_dir-

      # FIXME(blarsen): the next few steps should all be combined into a script
      #                 under scripts/, which can be easily invoked from a
      #                 working copy of the repo
      - name: Prepare for fuzzing
        run: |
          set -xu
          mkdir -p "$FUZZ_RUN_DIR/artifacts" "$FUZZ_RUN_DIR/corpus"
          cp fuzz/dict.txt "$FUZZ_RUN_DIR/"
          cp -r data/examples/*.dr "$FUZZ_RUN_DIR/corpus/"
          NUM_CORPUS_ITEMS=$(find "$FUZZ_RUN_DIR/corpus" -type f | wc -l | tr -d '[:blank:]')
          echo "$NUM_CORPUS_ITEMS items in corpus"

      - name: Fuzz

        # Note: we have to set these up manually, because the documented behavior
        #       for event inputs (exposing them via specially-named environment variables)
        #       doesn't seem to actually be correct.
        env:
          FUZZ_SECONDS: ${{ github.event.inputs.fuzz_seconds }}
          TIMEOUT_SECONDS: ${{ github.event.inputs.timeout_seconds }}
          MAX_LENGTH: ${{ github.event.inputs.max_length }}
          CORPUS_PRUNE_THRESHOLD: ${{ github.event.inputs.corpus_prune_threshold }}

        run: |
          set -xu
          if ! build/fuzz/fuzzer \
                 -max_total_time="${FUZZ_SECONDS:-${FUZZ_SECONDS_DEFAULT}}" \
                 -timeout="${TIMEOUT_SECONDS:-${TIMEOUT_SECONDS_DEFAULT}}" \
                 -max_len="${MAX_LENGTH:-${MAX_LENGTH_DEFAULT}}" \
                 -print_final_stats=1 \
                 -exact_artifact_path="$FUZZ_RUN_DIR/crasher.dr" \
                 -dict="$FUZZ_RUN_DIR/dict.txt" \
                 "$FUZZ_RUN_DIR/corpus"; then
            echo >&2 "Crash detected during fuzzing!"
            echo >&2 "Crashing input written to crasher.dr."
            echo >&2 "Base64-encoded crashing input:"
            base64 >&2 "$FUZZ_RUN_DIR/crasher.dr"
            echo >&2 "Minimizing crashing input..."
            scripts/minimize-fuzz-crasher "$FUZZ_RUN_DIR/crasher.dr"
            echo >&2 "Base64-encoded minimized crashing input:"
            base64 >&2 "$FUZZ_RUN_DIR/crasher.dr"
            exit 1
          fi
          NUM_CORPUS_ITEMS=$(find "$FUZZ_RUN_DIR/corpus" -type f | wc -l | tr -d '[:blank:]')
          # Note: `export` doesn't work here; you must use this special form.
          #       See https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
          echo "::set-env name=SHOULD_PRUNE_CORPUS::$(( NUM_CORPUS_ITEMS >= ${CORPUS_PRUNE_THRESHOLD:-${CORPUS_PRUNE_THRESHOLD_DEFAULT}} ))"

      - name: Prune fuzzer corpus
        if: env.SHOULD_PRUNE_CORPUS != 0
        run: |
          set -xu
          mv "$FUZZ_RUN_DIR/corpus" "$FUZZ_RUN_DIR/corpus.orig"
          mkdir -p "$FUZZ_RUN_DIR/corpus"
          build/fuzz/fuzzer -merge=1 "$FUZZ_RUN_DIR/corpus" "$FUZZ_RUN_DIR/corpus.orig"
          rm -rf "$FUZZ_RUN_DIR/corpus.orig"


      # This will allow us to manually download the fuzzer artifacts from the
      # GitHub UI if needed
      - name: Archive fuzzer artifacts
        uses: actions/upload-artifact@v2
        # We want to always upload artifacts, especially in the case of
        # failure, to aid in reproducing problems detected through fuzzing.
        if: ${{ always() }}
        with:
          name: fuzzer-artifacts
          path: ${{ env.FUZZ_RUN_DIR }}
